# Generated by Django 3.1.3 on 2025-07-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0002_reviewmodel_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='userful_num',
            new_name='useful_num',
        ),
    ]
