# Generated by Django 3.1.3 on 2025-07-27 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewpost', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
